# Generated by Django 4.2.2 on 2024-03-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="taskmanageruser",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="taskmanageruser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="taskmanageruser",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="taskmanageruser",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="TaskManagerUser",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
