# Generated by Django 4.2.2 on 2024-02-10 17:28

from django.contrib.auth.models import Group, Permission
from django.db import migrations


def create_groups(apps, schema_editor):
    # "Creator" group and "add_task" permission
    creator_group = Group.objects.create(name="Creator")
    add_task_permission = Permission.objects.get(codename="add_task")
    creator_group.permissions.add(add_task_permission)

    # "Editor" group with "change_task" permission
    editor_group = Group.objects.create(name="Editor")
    change_task_permission = Permission.objects.get(codename="change_task")
    editor_group.permissions.add(change_task_permission)

    # "Admin" group with all permissions
    admin_group = Group.objects.create(name="Admin")
    all_permissions = Permission.objects.filter(content_type__app_label="tasks")
    admin_group.permissions.set(all_permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
