# Generated by Django 4.2.2 on 2024-02-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_due_date_task_due_date_after_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="version",
            field=models.IntegerField(default=0),
        ),
    ]
